services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: cpf-db
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - cpf-network
  rabbit:
    image: rabbitmq:3-management
    restart: always
    container_name: 'cpf-rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - cpf-network
  cpf-backend:
    image: cpf-backend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - rabbit
    networks:
      - cpf-network

networks:
  cpf-network:
    driver: bridge
    name: cpf-network

volumes:
  rabbitmq_data: null
  db_data: null
